# Files
adapters: "/home/uibk/c7701178/local/bio/bbmap/resources/adapters.fa"
phiX: "/home/uibk/c7701178/local/bio/bbmap/resources/phix174_ill.ref.fa.gz"
## Rapid assembly (https://www.biorxiv.org/content/10.1101/2021.02.01.429177v1)
ref: "/home/uibk/c7701178/scratch/DAPHNIA/daphnia_snakemake_pbs/ref/dgal_ra_pb-target-and-other_ill-confilter.blobfilter.rmmt_sspace-lr3_lrgc3_pg3_pilon_3.simple.fasta"
## Canu assembly (Stuart Dennis)
#ref: "/home/uibk/c7701178/scratch/DAPHNIA/D_galeata_genome/Dgal_v1.0_canu_best.fasta"
## Flye assembly (Stuart Dennis)
#ref: "/home/uibk/c7701178/scratch/DAPHNIA/D_galeata_genome/Dgal_v1.0_flye_best.fasta"
